import Head from 'next/head'

import Product from '../components/parts/Product/Product'
import Header from '../components/parts/Header/Header'
import Container from '../components/ui/Container/Container'
import Grid from '../components/ui/Grid/Grid'
import Promo from '../components/parts/Promo/Promo'
import { GetServerSideProps } from 'next'
import { ProductType } from '../types/Product'

export default function Home({ data }: { data: ProductType[] }) {
	return (
		<>
			<Head>
				<title>Products List</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Header />
			<Container>
				<Grid>
					<Promo />
					{data.map(product => (
						<Product key={product.id} product={product} />
					))}
				</Grid>
			</Container>
		</>
	)
}

export const getServerSideProps: GetServerSideProps = async () => {
	const res = await fetch('https://fakestoreapi.com/products?limit=9')
	const data = await res.json()

	// Pass data to the page via props
	return { props: { data } }
}
